/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.daviapps.dcodeReader;

import com.daviapps.DCode.DCodeFile;

/**
 *
 * @author Davi
 */
public class MainForm extends javax.swing.JFrame {
    
    DCodeFile dFile;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        dFile = new DCodeFile("C:\\Users\\Davi\\Documents\\GitHub\\DCodeReader\\Prefs\\prefs.DCode");
        
        //dFile.setText("Conteudo teste");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JMenuBar();
        Menu_Arquivo = new javax.swing.JMenu();
        Arquivo_Novo = new javax.swing.JMenuItem();
        Arquivo_Abrir = new javax.swing.JMenuItem();
        Arquivo_Salvar = new javax.swing.JMenuItem();
        Arquivo_SalvarComo = new javax.swing.JMenuItem();
        Arquivo_Apagar = new javax.swing.JMenuItem();
        Arquivo_Sep1 = new javax.swing.JPopupMenu.Separator();
        Arquivo_Detalhes = new javax.swing.JMenuItem();
        Arquivo_Configs = new javax.swing.JMenuItem();
        Arquivo_Sep2 = new javax.swing.JPopupMenu.Separator();
        Arquivo_Sair = new javax.swing.JMenuItem();
        Menu_Editar = new javax.swing.JMenu();
        Editar_Undo = new javax.swing.JMenuItem();
        Editar_Endo = new javax.swing.JMenuItem();
        Menu_Ajuda = new javax.swing.JMenu();
        Ajuda_Ajuda = new javax.swing.JMenuItem();
        Ajuda_Sep1 = new javax.swing.JPopupMenu.Separator();
        Ajuda_Sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DCode Reader");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("MainForm"); // NOI18N

        Menu_Arquivo.setText("Arquivo");

        Arquivo_Novo.setText("Novo");
        Arquivo_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_NovoActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Novo);

        Arquivo_Abrir.setText("Abrir");
        Arquivo_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_AbrirActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Abrir);

        Arquivo_Salvar.setText("Salvar");
        Arquivo_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_SalvarActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Salvar);

        Arquivo_SalvarComo.setText("Salvar como");
        Arquivo_SalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_SalvarComoActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_SalvarComo);

        Arquivo_Apagar.setText("Apagar");
        Arquivo_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_ApagarActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Apagar);
        Menu_Arquivo.add(Arquivo_Sep1);

        Arquivo_Detalhes.setText("Detalhes");
        Arquivo_Detalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_DetalhesActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Detalhes);

        Arquivo_Configs.setText("Consigurações");
        Arquivo_Configs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_ConfigsActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Configs);
        Menu_Arquivo.add(Arquivo_Sep2);

        Arquivo_Sair.setText("Sair");
        Arquivo_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arquivo_SairActionPerformed(evt);
            }
        });
        Menu_Arquivo.add(Arquivo_Sair);

        Menu.add(Menu_Arquivo);

        Menu_Editar.setText("Editar");

        Editar_Undo.setText("Undo (Ctrl + Z)");
        Menu_Editar.add(Editar_Undo);

        Editar_Endo.setText("Endo (Ctrl + Y)");
        Menu_Editar.add(Editar_Endo);

        Menu.add(Menu_Editar);

        Menu_Ajuda.setText("Ajuda");

        Ajuda_Ajuda.setText("Ajuda [F1]");
        Ajuda_Ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajuda_AjudaActionPerformed(evt);
            }
        });
        Menu_Ajuda.add(Ajuda_Ajuda);
        Menu_Ajuda.add(Ajuda_Sep1);

        Ajuda_Sobre.setText("Sobre");
        Ajuda_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajuda_SobreActionPerformed(evt);
            }
        });
        Menu_Ajuda.add(Ajuda_Sobre);

        Menu.add(Menu_Ajuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Menu Arquivo
    
    private void Arquivo_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_NovoActionPerformed
        System.out.println("Novo");
    }//GEN-LAST:event_Arquivo_NovoActionPerformed

    private void Arquivo_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_AbrirActionPerformed
        System.out.println("Abrir");
    }//GEN-LAST:event_Arquivo_AbrirActionPerformed

    private void Arquivo_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_SalvarActionPerformed
        System.out.println("Salvar");
    }//GEN-LAST:event_Arquivo_SalvarActionPerformed

    private void Arquivo_SalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_SalvarComoActionPerformed
        System.out.println("Salvar como");
    }//GEN-LAST:event_Arquivo_SalvarComoActionPerformed

    private void Arquivo_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_ApagarActionPerformed
        System.out.println("Apagar");
    }//GEN-LAST:event_Arquivo_ApagarActionPerformed

    private void Arquivo_DetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_DetalhesActionPerformed
        if(dFile != null){
            new DCodeFileProps(this, dFile).show();
        }
        //System.out.println("Detalhes");
    }//GEN-LAST:event_Arquivo_DetalhesActionPerformed

    private void Arquivo_ConfigsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_ConfigsActionPerformed
        System.out.println("Configurações");
    }//GEN-LAST:event_Arquivo_ConfigsActionPerformed

    private void Arquivo_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arquivo_SairActionPerformed
        System.out.println("Sair");
    }//GEN-LAST:event_Arquivo_SairActionPerformed

    // Menu Ajuda
    
    private void Ajuda_AjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajuda_AjudaActionPerformed
        System.out.println("Ajuda");
    }//GEN-LAST:event_Ajuda_AjudaActionPerformed

    private void Ajuda_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajuda_SobreActionPerformed
        System.out.println("Sobre");
    }//GEN-LAST:event_Ajuda_SobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ajuda_Ajuda;
    private javax.swing.JPopupMenu.Separator Ajuda_Sep1;
    private javax.swing.JMenuItem Ajuda_Sobre;
    private javax.swing.JMenuItem Arquivo_Abrir;
    private javax.swing.JMenuItem Arquivo_Apagar;
    private javax.swing.JMenuItem Arquivo_Configs;
    private javax.swing.JMenuItem Arquivo_Detalhes;
    private javax.swing.JMenuItem Arquivo_Novo;
    private javax.swing.JMenuItem Arquivo_Sair;
    private javax.swing.JMenuItem Arquivo_Salvar;
    private javax.swing.JMenuItem Arquivo_SalvarComo;
    private javax.swing.JPopupMenu.Separator Arquivo_Sep1;
    private javax.swing.JPopupMenu.Separator Arquivo_Sep2;
    private javax.swing.JMenuItem Editar_Endo;
    private javax.swing.JMenuItem Editar_Undo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Menu_Ajuda;
    private javax.swing.JMenu Menu_Arquivo;
    private javax.swing.JMenu Menu_Editar;
    // End of variables declaration//GEN-END:variables
}
